jb_simple_page_front:
    resource: "@JbSimplePageBundle/Resources/config/routing/front.yml"

jb_simple_page_admin:
    resource: "@JbSimplePageBundle/Resources/config/routing/admin.yml"
    prefix: /admin