Jb\Bundle\SimplePageBundle\Model\Page:
    properties:
        title:
            - NotBlank: ~
            - Length:
                max: 255
        content:
            - NotBlank: ~
        metaTitle:
            - Length:
                max: 255
        metaDescription:
            - Length:
                max: 255