jb_simple_page_index:
    path: /page
    defaults: { _controller: jb_simple_page.admin.controller:indexAction }
    methods: [GET]

jb_simple_page_create:
    path: /page/create
    defaults: { _controller: jb_simple_page.admin.controller:createAction }
    methods: [GET, POST]

jb_simple_page_edit:
    path: /page/{slug}/edit
    defaults: { _controller: jb_simple_page.admin.controller:editAction }
    methods: [GET, POST]

jb_simple_page_remove:
    path: /page/{slug}/remove
    defaults: { _controller: jb_simple_page.admin.controller:removeAction }
    methods: [POST]